"""add_booking_id_to_payouts

Revision ID: 7bbbbfd01949
Revises: e38f3dc785c1
Create Date: 2026-01-30 11:32:19.946468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbbbfd01949'
down_revision: Union[str, None] = 'e38f3dc785c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_payouts', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'host_payouts', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'host_payouts', type_='foreignkey')
    op.drop_column('host_payouts', 'booking_id')
    # ### end Alembic commands ###
