"""Add dispute chargeback and ops role support

Revision ID: a2d716e66017
Revises: bd6555bab5e4
Create Date: 2026-01-30 19:20:59.288441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d716e66017'
down_revision: Union[str, None] = 'bd6555bab5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('resolution_type', sa.String(length=30), nullable=True))
    op.add_column('disputes', sa.Column('payout_adjusted', sa.Integer(), nullable=False))
    op.add_column('disputes', sa.Column('resolved_by', sa.UUID(), nullable=True))
    op.add_column('disputes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'disputes', 'users', ['resolved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_column('disputes', 'updated_at')
    op.drop_column('disputes', 'resolved_by')
    op.drop_column('disputes', 'payout_adjusted')
    op.drop_column('disputes', 'resolution_type')
    # ### end Alembic commands ###
