"""Add financial settlement tables

Revision ID: bd6555bab5e4
Revises: 7bbbbfd01949
Create Date: 2026-01-30 18:27:12.793902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6555bab5e4'
down_revision: Union[str, None] = '7bbbbfd01949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
