"""add_gateway_fee_amount_to_payments

Revision ID: e38f3dc785c1
Revises: 002_seed_amenities
Create Date: 2026-01-30 09:38:59.391159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38f3dc785c1'
down_revision: Union[str, None] = '002_seed_amenities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('booking_extensions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('booking_extensions', 'requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'adults',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'children',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'infants',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'cleaning_fee',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'service_fee',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'taxes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('bookings', 'refund_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'booked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('calendar_blocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cohost_permissions', 'can_manage_bookings',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cohost_permissions', 'can_manage_calendar',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cohost_permissions', 'can_manage_pricing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cohost_permissions', 'can_message_guests',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cohost_permissions', 'can_view_payouts',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cohost_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'is_archived_by_guest',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('conversations', 'is_archived_by_host',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('disputes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('disputes', 'refund_granted',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('host_payouts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('host_payouts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('host_payouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('house_rules', 'is_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('listing_photos', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listing_photos', 'is_cover',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('listing_photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listings', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'beds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'bathrooms',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               nullable=False)
    op.alter_column('listings', 'cleaning_fee',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'service_fee_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('listings', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('listings', 'cancellation_policy',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('listings', 'check_in_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('listings', 'check_out_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('listings', 'min_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'max_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'instant_booking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('listings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('listings', 'whatsapp_ai_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('listings', 'sync_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'push_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('payments', sa.Column('gateway_fee_amount', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('payments', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pricing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refunds', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_identity', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_identity', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'preferred_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('users', 'loyalty_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'total_stays',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'total_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'total_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'total_stays',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'loyalty_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'preferred_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'is_phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_identity', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_identity', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refunds', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pricing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('payments', 'gateway_fee_amount')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'push_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'sync_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('listings', 'whatsapp_ai_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('listings', 'instant_booking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('listings', 'max_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'min_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'check_out_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('listings', 'check_in_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('listings', 'cancellation_policy',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('listings', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('listings', 'service_fee_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('listings', 'cleaning_fee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'bathrooms',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               nullable=True)
    op.alter_column('listings', 'beds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listing_photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listing_photos', 'is_cover',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('listing_photos', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('house_rules', 'is_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('host_payouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('host_payouts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('host_payouts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('disputes', 'refund_granted',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('disputes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'is_archived_by_host',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('conversations', 'is_archived_by_guest',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cohost_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cohost_permissions', 'can_view_payouts',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cohost_permissions', 'can_message_guests',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cohost_permissions', 'can_manage_pricing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cohost_permissions', 'can_manage_calendar',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cohost_permissions', 'can_manage_bookings',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('calendar_blocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'booked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'refund_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bookings', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('bookings', 'taxes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'service_fee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'cleaning_fee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'infants',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'children',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'adults',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking_extensions', 'requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('booking_extensions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
